{
    "formName":"测试一",
    "formCode":"code_1",
    "displayText":"单元测试",
    "needFlow":false,
    "columns":[{
        "id":1,
        "name":"age",
        "DisplayText":"年龄",
        "type":{
            "id":1,
            "len":0
        }
    },{
        "id":2,
        "name":"salary",
        "DisplayText":"薪水",
        "type":{
            "id":2,
            "len":0
        }
    },{
        "id":3,
        "name":"point",
        "DisplayText":"得分",
        "type":{
            "id":3,
            "len":0
        }
    },{
        "id":4,
        "name":"name",
        "DisplayText":"姓名",
        "type":{
            "id":4,
            "len":100
        }
    },{
        "id":5,
        "name":"is_student",
        "DisplayText":"是否学生",
        "type":{
            "id":5,
            "len":0
        }
    },{
        "id":6,
        "name":"attachment_id",
        "DisplayText":"附件",
        "type":{
            "id":6,
            "len":0
        }
    }],
    "layout":{
        "column":2,
        "details":[
            [1,3],
            [2,4],
            [5,-1],
            [6,0]
        ]
    }
}